/*
    by korenkonder
    GitHub/GitLab: korenkonder
*/

#include "graphics.h"

classes_struct graphics_classes[] = {
    {
        .name    = "Background Color##Graphics",
        .flags   = CLASSES_IN_CONTEXT_MENU,
        .init    = graphics_background_color_init,
        .draw    = CLASSES_STRUCT_NO_FUNC,
        .drop    = CLASSES_STRUCT_NO_FUNC,
        .hide    = CLASSES_STRUCT_NO_FUNC,
        .imgui   = graphics_background_color_imgui,
        .input   = graphics_background_color_input,
        .render  = graphics_background_color_render,
        .show    = CLASSES_STRUCT_NO_FUNC,
        .sound   = CLASSES_STRUCT_NO_FUNC,
        .dispose = graphics_background_color_dispose,
        .data    = {
            .lock = 0,
            .flags = CLASS_DISPOSED | CLASS_HIDDEN,
            .imgui_focus = false,
            .data = CLASS_DATA_NO_DATA,
        },
        .sub_classes = 0,
        .sub_classes_count = 0,
    },
    {
        .name    = "Post Process##Graphics",
        .flags   = CLASSES_IN_CONTEXT_MENU,
        .init    = graphics_post_process_init,
        .draw    = CLASSES_STRUCT_NO_FUNC,
        .drop    = CLASSES_STRUCT_NO_FUNC,
        .hide    = CLASSES_STRUCT_NO_FUNC,
        .imgui   = graphics_post_process_imgui,
        .input   = graphics_post_process_input,
        .render  = graphics_post_process_render,
        .show    = CLASSES_STRUCT_NO_FUNC,
        .sound   = CLASSES_STRUCT_NO_FUNC,
        .dispose = graphics_post_process_dispose,
        .data    = {
            .lock = 0,
            .flags = CLASS_DISPOSED | CLASS_HIDDEN,
            .imgui_focus = false,
            .data = CLASS_DATA_NO_DATA,
        },
        .sub_classes = 0,
        .sub_classes_count = 0,
    },
    {
        .name    = "Glitter##Graphics",
        .flags   = CLASSES_IN_CONTEXT_MENU,
        .init    = graphics_glitter_init,
        .draw    = CLASSES_STRUCT_NO_FUNC,
        .drop    = CLASSES_STRUCT_NO_FUNC,
        .hide    = CLASSES_STRUCT_NO_FUNC,
        .imgui   = graphics_glitter_imgui,
        .input   = graphics_glitter_input,
        .render  = graphics_glitter_render,
        .show    = CLASSES_STRUCT_NO_FUNC,
        .sound   = CLASSES_STRUCT_NO_FUNC,
        .dispose = graphics_glitter_dispose,
        .data    = {
            .lock = 0,
            .flags = CLASS_DISPOSED | CLASS_HIDDEN,
            .imgui_focus = false,
            .data = CLASS_DATA_NO_DATA,
        },
        .sub_classes = 0,
        .sub_classes_count = 0,
    },
    {
        .name    = "Render Settings##Graphics",
        .flags   = CLASSES_IN_CONTEXT_MENU,
        .init    = graphics_render_settings_init,
        .draw    = CLASSES_STRUCT_NO_FUNC,
        .drop    = CLASSES_STRUCT_NO_FUNC,
        .hide    = CLASSES_STRUCT_NO_FUNC,
        .imgui   = graphics_render_settings_imgui,
        .input   = graphics_render_settings_input,
        .render  = graphics_render_settings_render,
        .show    = CLASSES_STRUCT_NO_FUNC,
        .sound   = CLASSES_STRUCT_NO_FUNC,
        .dispose = graphics_render_settings_dispose,
        .data    = {
            .lock = 0,
            .flags = CLASS_DISPOSED | CLASS_HIDDEN,
            .imgui_focus = false,
            .data = CLASS_DATA_NO_DATA,
        },
        .sub_classes = 0,
        .sub_classes_count = 0,
    },
};
